import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center ">
        <div className="m-2 bg-slate-200 w-full h-20 flex flex-row justify-center">
          <div className="font-sans justify-center w-max h-full text-center items-center">Internatioanl Growers Association</div>
          <div className="my-4 mx-3 border-slate-100 border-[0.1rem] text-slate-100 rounded-lg w-full flex items-center justify-center justify-items-center"><p className="mb-[0.15rem]">Corporate</p></div>
          <div className="my-4 mx-2 bg-slate-600 w-full flex items-center justify-center"><p>fff</p></div>
          <div className="my-4 mx-2 bg-slate-600 w-full flex items-center justify-center"><p>fff</p></div>
          <div className="my-4 mx-3 border-slate-100 border-[0.1rem] text-slate-100 rounded-lg w-full flex items-center justify-center justify-items-center flex-shrink"><p className="mb-[0.15rem]">Login</p></div>
        </div>
      <div>
        <div className="mx-auto justify-center text-3xl mt-6 text-center font-lobster">
          <p className="font-lobster">Lowest and Local</p>
        </div>
        <div className="grid grid-cols-3 gap-4 mx-auto mt-6 px-36">
          <img className="rounded-lg w-max h-auto" src="https://www.iga.com/hubfs/Fettuccinni%20Alfredo%20CARD.png" alt="veggies"></img>
          <img className="rounded-lg w-max h-auto" src="https://www.iga.com/hubfs/Fettuccinni%20Alfredo%20CARD.png" alt="veggies"></img>
          <img className="rounded-lg w-max " src="https://www.iga.com/hubfs/Fettuccinni%20Alfredo%20CARD.png" alt="veggies"></img>
        </div>

        <div className="w-full bg-stone-500 border-t-stone-400 border-spacing-3 s-2 border-t-4 h-96 mt-24">
          <div className="m-6 grid grid-cols-2">
              <div className="justify-center w-full font-sans ml-12 flex flex-col gap-8">
                <a className="text-gray-200 underline-offset-4 underline hover:underline-offset-1 transition-all">About</a>
                <a className="text-gray-200 underline-offset-4 underline hover:underline-offset-1 transition-all">Corporate</a>
                <a className="text-gray-200 underline-offset-4 underline hover:underline-offset-1 transition-all">Contact Info</a>
              </div>
            <div className="justify-center w-full font-sans flex flex-col">
              <a className="text-slate-200 w-full">fff</a>
              <a className="text-slate-200 underline w-full">ffff</a>
            </div>
          </div>

        </div>

        
        
      </div>
      </main>
    </>
  );
};

export default Home;
